# Generated by Django 5.0.1 on 2025-10-23 19:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the tournament",
                        max_length=255,
                        verbose_name="Tournament Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the tournament",
                        null=True,
                        verbose_name="About this Tournament",
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        help_text="Name of the contact person",
                        max_length=255,
                        verbose_name="Contact Name",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        help_text="Contact phone number",
                        max_length=20,
                        verbose_name="Contact Phone",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        help_text="Contact email address",
                        max_length=254,
                        verbose_name="Contact Email",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        help_text="Tournament start date and time", verbose_name="Start Date"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        help_text="Tournament end date and time", verbose_name="End Date"
                    ),
                ),
                (
                    "registration_deadline",
                    models.DateTimeField(
                        help_text="Last date to register for the tournament",
                        verbose_name="Registration Deadline",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        help_text="Full address of the tournament location",
                        max_length=500,
                        null=True,
                        verbose_name="Address",
                    ),
                ),
                (
                    "street_number",
                    models.CharField(
                        blank=True,
                        help_text="Street or door number",
                        max_length=100,
                        null=True,
                        verbose_name="Street/Door Number",
                    ),
                ),
                (
                    "street_location",
                    models.CharField(
                        blank=True,
                        help_text="Street or location details",
                        max_length=200,
                        null=True,
                        verbose_name="Street/Location",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        help_text="City where the tournament takes place",
                        max_length=100,
                        verbose_name="City",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        help_text="State or province",
                        max_length=100,
                        null=True,
                        verbose_name="State",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        help_text="Country where the tournament takes place",
                        max_length=100,
                        verbose_name="Country",
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True,
                        help_text="Postal or ZIP code",
                        max_length=20,
                        null=True,
                        verbose_name="Postal Code",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("registration_open", "Registration Open"),
                            ("registration_closed", "Registration Closed"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the tournament is active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tournaments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization organizing this tournament",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournaments",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tournament",
                "verbose_name_plural": "Tournaments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TournamentDivision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the division or event",
                        max_length=255,
                        verbose_name="Event Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the division",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("knockout", "Knockout"),
                            ("league", "League"),
                            ("round_robin", "Round Robin"),
                        ],
                        help_text="Tournament format for this division",
                        max_length=20,
                        verbose_name="Format",
                    ),
                ),
                (
                    "max_participants",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum number of participants allowed",
                        null=True,
                        verbose_name="Maximum Participants",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("any", "Any"), ("male", "Male"), ("female", "Female")],
                        default="any",
                        help_text="Gender restriction for participants",
                        max_length=10,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "participant_type",
                    models.CharField(
                        choices=[("single", "Single"), ("team", "Team")],
                        help_text="Type of participants (individual or team)",
                        max_length=10,
                        verbose_name="Participant Type",
                    ),
                ),
                (
                    "born_after",
                    models.DateField(
                        blank=True,
                        help_text="Participants must be born after this date",
                        null=True,
                        verbose_name="Born After",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the division is active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "tournament",
                    models.ForeignKey(
                        help_text="Tournament this division belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="divisions",
                        to="tournaments.tournament",
                        verbose_name="Tournament",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tournament Division",
                "verbose_name_plural": "Tournament Divisions",
                "ordering": ["tournament", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="tournament",
            index=models.Index(fields=["organization"], name="tournaments_organiz_eaab22_idx"),
        ),
        migrations.AddIndex(
            model_name="tournament",
            index=models.Index(fields=["status"], name="tournaments_status_c3a7bb_idx"),
        ),
        migrations.AddIndex(
            model_name="tournament",
            index=models.Index(fields=["start_date"], name="tournaments_start_d_242af9_idx"),
        ),
        migrations.AddIndex(
            model_name="tournament",
            index=models.Index(fields=["is_active"], name="tournaments_is_acti_bb45af_idx"),
        ),
        migrations.AddIndex(
            model_name="tournamentdivision",
            index=models.Index(fields=["tournament"], name="tournaments_tournam_a9e579_idx"),
        ),
        migrations.AddIndex(
            model_name="tournamentdivision",
            index=models.Index(fields=["format"], name="tournaments_format_94cc12_idx"),
        ),
        migrations.AddIndex(
            model_name="tournamentdivision",
            index=models.Index(fields=["participant_type"], name="tournaments_partici_69a65c_idx"),
        ),
        migrations.AddIndex(
            model_name="tournamentdivision",
            index=models.Index(fields=["is_active"], name="tournaments_is_acti_e8eebc_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="tournamentdivision",
            unique_together={("tournament", "name")},
        ),
    ]
