# Generated by Django 5.0.1 on 2025-10-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournamentdivision",
            name="participant_type",
            field=models.CharField(
                choices=[("single", "Single"), ("doubles", "Doubles")],
                help_text="Type of participants (individual or team)",
                max_length=10,
                verbose_name="Participant Type",
            ),
        ),
    ]
