# Generated by Django 5.0.1 on 2025-10-28 01:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0002_alter_tournamentdivision_participant_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Involvement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        help_text="Registration status",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "paid",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the player has paid the registration fee",
                        verbose_name="Paid",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Registered At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the involvement was approved",
                        null=True,
                        verbose_name="Approved At",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who approved this involvement",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_involvements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        help_text="Division the player is involved in",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="involvements",
                        to="tournaments.tournamentdivision",
                        verbose_name="Division",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        help_text="Player involved in the tournament",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_involvements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Player",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        help_text="Tournament the player is involved in",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="involvements",
                        to="tournaments.tournament",
                        verbose_name="Tournament",
                    ),
                ),
            ],
            options={
                "verbose_name": "Involvement",
                "verbose_name_plural": "Involvements",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["tournament"], name="tournaments_tournam_ab6096_idx"),
                    models.Index(fields=["player"], name="tournaments_player__43e8e6_idx"),
                    models.Index(fields=["division"], name="tournaments_divisio_383aaa_idx"),
                    models.Index(fields=["status"], name="tournaments_status_670e35_idx"),
                    models.Index(fields=["paid"], name="tournaments_paid_67cb80_idx"),
                ],
                "unique_together": {("tournament", "player", "division")},
            },
        ),
    ]
