# Generated by Django 5.0.1 on 2025-10-28 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0003_involvement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="involvement",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                help_text="Partner for doubles tournaments",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tournament_partnerships",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Partner",
            ),
        ),
        migrations.AlterField(
            model_name="involvement",
            name="player",
            field=models.ForeignKey(
                help_text="Primary player involved in the tournament",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tournament_involvements",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Player",
            ),
        ),
        migrations.AddIndex(
            model_name="involvement",
            index=models.Index(fields=["partner"], name="tournaments_partner_e82d7c_idx"),
        ),
    ]
