# Generated by Django 5.0.1 on 2025-10-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0004_add_partner_to_involvement"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Logo o imagen representativa del torneo",
                null=True,
                upload_to="tournament_logos/",
                verbose_name="Logo del Torneo",
            ),
        ),
    ]
