# Generated by Django 5.0.1 on 2025-11-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0006_alter_tournament_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournamentdivision",
            name="format",
            field=models.CharField(
                choices=[
                    ("knockout", "Single Elimination"),
                    ("double_slash", "Double Elimination"),
                    ("round_robin", "Round Robin"),
                ],
                help_text="Tournament format for this division",
                max_length=20,
                verbose_name="Format",
            ),
        ),
    ]
