# Generated by Django 5.0.1 on 2025-11-23 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0003_playerprofile_avatar"),
        ("tournaments", "0007_alter_tournamentdivision_format"),
    ]

    operations = [
        migrations.AlterField(
            model_name="involvement",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                help_text="Partner for doubles tournaments",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tournament_partnerships",
                to="players.playerprofile",
                verbose_name="Partner",
            ),
        ),
        migrations.AlterField(
            model_name="involvement",
            name="player",
            field=models.ForeignKey(
                help_text="Primary player involved in the tournament",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tournament_involvements",
                to="players.playerprofile",
                verbose_name="Player",
            ),
        ),
    ]
