# Generated by Django 5.0.1 on 2025-11-28 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0008_alter_involvement_partner_alter_involvement_player"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentdivision",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="Whether the division is published",
                verbose_name="Published",
            ),
        ),
        migrations.AddField(
            model_name="tournamentdivision",
            name="published_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the division was published",
                null=True,
                verbose_name="Published At",
            ),
        ),
        migrations.AddField(
            model_name="tournamentdivision",
            name="published_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who published this division",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="published_divisions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Published By",
            ),
        ),
    ]
