# Generated by Django 5.0.1 on 2025-12-06 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0009_tournamentdivision_is_published_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="banner",
            field=models.ImageField(
                blank=True,
                help_text="Banner o imagen promocional del torneo",
                null=True,
                upload_to="tournament_banners/",
                verbose_name="Banner del Torneo",
            ),
        ),
    ]
