# Generated by Django 5.0.1 on 2025-12-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0010_tournament_banner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="banner",
            field=models.ImageField(
                blank=True,
                help_text="Tournament banner or promotional image",
                null=True,
                upload_to="tournament_banners/",
                verbose_name="Tournament Banner",
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Tournament logo or representative image",
                null=True,
                upload_to="tournament_logos/",
                verbose_name="Tournament Logo",
            ),
        ),
    ]
