# Generated by Django 5.0.1 on 2026-01-24 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0013_tournamentgroup_groupstanding"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="groupstanding",
            new_name="tournaments_group_i_beded4_idx",
            old_name="tournaments_group__def456_idx",
        ),
        migrations.RenameIndex(
            model_name="groupstanding",
            new_name="tournaments_involve_86ff8a_idx",
            old_name="tournaments_involv_ghi789_idx",
        ),
        migrations.RenameIndex(
            model_name="groupstanding",
            new_name="tournaments_positio_0ce64b_idx",
            old_name="tournaments_positio_jkl012_idx",
        ),
        migrations.RenameIndex(
            model_name="groupstanding",
            new_name="tournaments_global__3cfd53_idx",
            old_name="tournaments_global__mno345_idx",
        ),
        migrations.RenameIndex(
            model_name="groupstanding",
            new_name="tournaments_points_65d688_idx",
            old_name="tournaments_points_pqr678_idx",
        ),
        migrations.RenameIndex(
            model_name="tournamentgroup",
            new_name="tournaments_divisio_c15c47_idx",
            old_name="tournaments_divisio_abc123_idx",
        ),
        migrations.RenameIndex(
            model_name="tournamentgroup",
            new_name="tournaments_group_n_79a759_idx",
            old_name="tournaments_group_n_xyz789_idx",
        ),
    ]
