# Generated by Django 5.0.1 on 2026-01-31 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0015_involvement_knockout_points"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="involvement",
            new_name="tournaments_knockou_94b9a3_idx",
            old_name="tournaments_knockou_abc123_idx",
        ),
    ]
