# Generated by Django 5.0.1 on 2025-10-21 22:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("first_name", models.CharField(max_length=150, verbose_name="First Name")),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=150, verbose_name="Middle Name"),
                ),
                ("last_name", models.CharField(max_length=150, verbose_name="Last Name")),
                (
                    "short_bio",
                    models.CharField(blank=True, max_length=200, verbose_name="Short Bio"),
                ),
                ("long_description", models.TextField(blank=True, verbose_name="Long Description")),
                (
                    "date_of_birth",
                    models.DateField(blank=True, null=True, verbose_name="Date of Birth"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("prefer_not_to_say", "Prefer not to say"),
                        ],
                        max_length=20,
                        verbose_name="Gender",
                    ),
                ),
                ("nationality", models.CharField(max_length=100, verbose_name="Nationality")),
                (
                    "instagram_url",
                    models.URLField(blank=True, max_length=255, verbose_name="Instagram URL"),
                ),
                (
                    "facebook_url",
                    models.URLField(blank=True, max_length=255, verbose_name="Facebook URL"),
                ),
                (
                    "linkedin_url",
                    models.URLField(blank=True, max_length=255, verbose_name="LinkedIn URL"),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Must match user email", max_length=254, verbose_name="Email"
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, verbose_name="Phone Number")),
                (
                    "document_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("dni", "DNI"),
                            ("passport", "Passport"),
                            ("driver_license", "Driver License"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Document Type",
                    ),
                ),
                (
                    "document_number",
                    models.CharField(blank=True, max_length=50, verbose_name="Document Number"),
                ),
                (
                    "street_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Street / Door Number"
                    ),
                ),
                (
                    "street_location",
                    models.CharField(blank=True, max_length=255, verbose_name="Street / Location"),
                ),
                ("city", models.CharField(blank=True, max_length=100, verbose_name="City")),
                ("state", models.CharField(blank=True, max_length=100, verbose_name="State")),
                ("country", models.CharField(blank=True, max_length=100, verbose_name="Country")),
                (
                    "postal_code",
                    models.CharField(blank=True, max_length=20, verbose_name="PIN / Postal Code"),
                ),
                (
                    "height_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Height (cm)",
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Weight (kg)",
                    ),
                ),
                (
                    "handedness",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("left_handed", "Left-Handed"),
                            ("right_handed", "Right-Handed"),
                            ("ambidextrous", "Ambidextrous"),
                        ],
                        max_length=20,
                        verbose_name="Handedness",
                    ),
                ),
                (
                    "emergency_contact_first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Emergency Contact First Name"
                    ),
                ),
                (
                    "emergency_contact_last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Emergency Contact Last Name"
                    ),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Emergency Contact Phone"
                    ),
                ),
                (
                    "emergency_contact_relationship",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Emergency Contact Relationship"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Player Profile",
                "verbose_name_plural": "Player Profiles",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user"], name="players_pla_user_id_0a96ec_idx"),
                    models.Index(fields=["email"], name="players_pla_email_0536d2_idx"),
                ],
            },
        ),
    ]
