# Generated by Django 5.0.1 on 2025-11-23 01:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geographical", "0001_initial"),
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerprofile",
            name="nationality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="geographical.country",
                verbose_name="Nationality",
            ),
        ),
        migrations.CreateModel(
            name="PlayerConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "accepted_privacy_policy",
                    models.BooleanField(default=False, verbose_name="Accepted Privacy Policy"),
                ),
                (
                    "privacy_policy_version",
                    models.CharField(max_length=20, verbose_name="Privacy Policy Version"),
                ),
                (
                    "accepted_terms",
                    models.BooleanField(default=False, verbose_name="Accepted Terms"),
                ),
                ("terms_version", models.CharField(max_length=20, verbose_name="Terms Version")),
                ("consent_accepted_at", models.DateTimeField(verbose_name="Consent Accepted At")),
                ("terms_accepted_at", models.DateTimeField(verbose_name="Terms Accepted At")),
                (
                    "consent_ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Consent IP Address"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to="players.playerprofile",
                        verbose_name="Profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Player Consent",
                "verbose_name_plural": "Player Consents",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["profile"], name="players_pla_profile_4f2083_idx"),
                    models.Index(
                        fields=["consent_accepted_at"], name="players_pla_consent_684ab8_idx"
                    ),
                ],
            },
        ),
    ]
