# Generated by Django 5.0.1 on 2025-11-23 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0002_alter_playerprofile_nationality_playerconsent"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Imagen de perfil del jugador",
                null=True,
                upload_to="player_avatars/",
                verbose_name="Avatar",
            ),
        ),
    ]
