# Generated by Django 5.0.1 on 2025-11-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0004_make_user_optional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerprofile",
            name="email",
            field=models.EmailField(
                help_text="Must match user email", max_length=254, unique=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="playerprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("prefer_not_to_say", "Prefer not to say"),
                ],
                max_length=20,
                null=True,
                verbose_name="Gender",
            ),
        ),
    ]
