# Generated by Django 5.0.1 on 2025-11-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0005_alter_playerprofile_email_alter_playerprofile_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                max_length=20,
                null=True,
                verbose_name="Gender",
            ),
        ),
    ]
