# Generated by Django 5.0.1 on 2025-12-11 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0006_alter_playerprofile_gender"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Player profile image",
                null=True,
                upload_to="player_avatars/",
                verbose_name="Avatar",
            ),
        ),
        migrations.AlterField(
            model_name="playerprofile",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
