# Generated by Django 5.0.1 on 2026-01-12 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_alter_playerprofile_avatar_alter_playerprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='blood_type',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Blood Type'),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='health_insurance',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Health Insurance'),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='medical_conditions',
            field=models.TextField(blank=True, help_text='Allergies, chronic conditions, etc.', null=True, verbose_name='Medical Conditions'),
        ),
    ]
