# Generated by Django 5.0.1 on 2026-01-13 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0008_playerprofile_blood_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerprofile",
            name="shirt_size",
            field=models.CharField(blank=True, max_length=20, verbose_name="Shirt Size"),
        ),
    ]
