# Generated by Django 5.0.1 on 2025-11-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Country Name"),
                ),
                (
                    "phone_code",
                    models.CharField(
                        help_text="International phone code (e.g., +1, +51, +34)",
                        max_length=10,
                        verbose_name="Phone Code",
                    ),
                ),
                (
                    "flag",
                    models.CharField(
                        blank=True,
                        help_text="Flag emoji or URL",
                        max_length=10,
                        verbose_name="Flag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
                "ordering": ["name"],
                "indexes": [models.Index(fields=["name"], name="geographica_name_666cae_idx")],
            },
        ),
    ]
