# Generated by Django 5.0.1 on 2025-12-11 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="payment",
            new_name="payments_pa_tournam_02464a_idx",
            old_name="payments_pa_tournam_idx",
        ),
        migrations.RenameIndex(
            model_name="payment",
            new_name="payments_pa_is_acti_b97bef_idx",
            old_name="payments_pa_is_acti_idx",
        ),
    ]
