# Generated by Django 5.0.1 on 2025-12-11 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_paymenttransaction"),
        ("payments", "0002_rename_payments_pa_tournam_idx_payments_pa_tournam_02464a_idx_and_more"),
    ]

    operations = []
