# Generated by Django 5.0.1 on 2025-12-11 05:01

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_merge_20251211_0001"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="paymenttransaction",
            new_name="payments_pa_involve_489cb6_idx",
            old_name="payments_pa_involve_idx",
        ),
        migrations.RenameIndex(
            model_name="paymenttransaction",
            new_name="payments_pa_status_b6726a_idx",
            old_name="payments_pa_status_idx",
        ),
        migrations.RenameIndex(
            model_name="paymenttransaction",
            new_name="payments_pa_transac_c1fd68_idx",
            old_name="payments_pa_transac_idx",
        ),
        migrations.RenameIndex(
            model_name="paymenttransaction",
            new_name="payments_pa_payment_a4dd44_idx",
            old_name="payments_pa_payment_idx",
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Payment amount",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Amount",
            ),
        ),
    ]
