# Generated by Django 5.0.1 on 2025-12-11 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_move_payment_to_division"),
        ("payments", "0004_rename_payments_pa_involve_idx_payments_pa_involve_489cb6_idx_and_more"),
    ]

    operations = []
