# Generated by Django 5.0.1 on 2025-12-11 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_merge_20251211_0009"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="payment",
            name="payments_pa_tournam_02464a_idx",
        ),
        migrations.RenameIndex(
            model_name="payment",
            new_name="payments_pa_divisio_8f3588_idx",
            old_name="payments_pa_division_idx",
        ),
    ]
