# Generated by Django 5.0.1 on 2025-12-11 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_add_tournament_to_payment"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="payment",
            new_name="payments_pa_tournam_02464a_idx",
            old_name="payments_pa_tournament_idx",
        ),
        migrations.AlterField(
            model_name="payment",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether payment subscription is active",
                verbose_name="Active",
            ),
        ),
    ]
