# Generated by Django 5.0.1 on 2025-12-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "payments",
            "0008_rename_payments_pa_tournament_idx_payments_pa_tournam_02464a_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_information",
            field=models.TextField(
                blank=True,
                help_text="Payment information for the tournament",
                null=True,
                verbose_name="Payment Information",
            ),
        ),
    ]
