# Generated manually for changing PaymentTransaction.involvement from ForeignKey to ManyToMany

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models
from decimal import Decimal


def migrate_involvement_to_manytomany(apps, schema_editor):
    """Migrate existing PaymentTransaction.involvement to ManyToMany."""
    PaymentTransaction = apps.get_model('payments', 'PaymentTransaction')
    db_alias = schema_editor.connection.alias
    
    # Get all payment transactions with their old involvement_id using raw SQL
    with schema_editor.connection.cursor() as cursor:
        # Use the actual table name
        cursor.execute(
            "SELECT id, involvement_id FROM payments_paymenttransaction WHERE involvement_id IS NOT NULL"
        )
        rows = cursor.fetchall()
        
        # The through table name is automatically generated by Django
        # Format: <app>_<model>_<field>
        # In this case: payments_paymenttransaction_involvements
        for transaction_id, involvement_id in rows:
            # Try to insert, ignore if already exists
            try:
                cursor.execute(
                    """
                    INSERT INTO payments_paymenttransaction_involvements 
                    (paymenttransaction_id, involvement_id)
                    VALUES (%s, %s)
                    """,
                    [transaction_id, involvement_id]
                )
            except Exception:
                # Relationship might already exist, skip
                pass


def reverse_migrate_involvement_to_manytomany(apps, schema_editor):
    """Reverse migration: create ForeignKey from first ManyToMany involvement."""
    PaymentTransaction = apps.get_model('payments', 'PaymentTransaction')
    db_alias = schema_editor.connection.alias
    
    # This is a no-op because we can't restore the ForeignKey without data loss
    # The reverse migration will fail if there are transactions with multiple involvements
    pass


def populate_subtotal_and_discount(apps, schema_editor):
    """Populate subtotal and total_discount from existing fields."""
    PaymentTransaction = apps.get_model('payments', 'PaymentTransaction')
    db_alias = schema_editor.connection.alias
    
    from decimal import Decimal
    
    # For existing transactions, set subtotal = subscription_fee
    # and total_discount = early_payment_discount + second_category_discount
    transactions = PaymentTransaction.objects.using(db_alias).all()
    for transaction in transactions:
        transaction.subtotal = transaction.subscription_fee
        transaction.total_discount = (
            Decimal(str(transaction.early_payment_discount)) +
            Decimal(str(transaction.second_category_discount))
        )
        transaction.save(update_fields=['subtotal', 'total_discount'])


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_payment_payment_information'),
        ('tournaments', '0010_tournament_banner'),
    ]

    operations = [
        # Step 1: Add new ManyToMany field (initially null=True to allow data migration)
        migrations.AddField(
            model_name='paymenttransaction',
            name='involvements',
            field=models.ManyToManyField(
                blank=True,
                help_text='Involvements this payment is for',
                related_name='payment_transactions',
                to='tournaments.involvement',
                verbose_name='Involvements'
            ),
        ),
        # Step 2: Migrate data from ForeignKey to ManyToMany
        migrations.RunPython(
            migrate_involvement_to_manytomany,
            reverse_migrate_involvement_to_manytomany,
        ),
        # Step 3: Add new fields (subtotal and total_discount) with default values
        migrations.AddField(
            model_name='paymenttransaction',
            name='subtotal',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                help_text='Subtotal before discounts (sum of all subscription fees)',
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal('0.00'))],
                verbose_name='Subtotal'
            ),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='total_discount',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                help_text='Total discount applied (early payment + second category)',
                max_digits=10,
                verbose_name='Total Discount'
            ),
        ),
        # Step 4: Populate subtotal and total_discount from existing fields
        migrations.RunPython(
            populate_subtotal_and_discount,
            migrations.RunPython.noop,
        ),
        # Step 5: Remove old ForeignKey field
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='involvement',
        ),
        # Step 6: Remove old index on involvement (already handled by RemoveField)
    ]

