# Generated by Django 5.0.1 on 2025-12-16 20:54

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0010_change_payment_transaction_to_manytomany"),
        ("tournaments", "0011_alter_tournament_banner_alter_tournament_logo"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="paymenttransaction",
            name="payments_pa_involve_489cb6_idx",
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Payment amount (total)",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Amount",
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="involvements",
            field=models.ManyToManyField(
                help_text="Involvements this payment is for",
                related_name="payment_transactions",
                to="tournaments.involvement",
                verbose_name="Involvements",
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="subscription_fee",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Total subscription fee (sum of all subscription fees)",
                max_digits=10,
                verbose_name="Subscription Fee",
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Subtotal before discounts (sum of all subscription fees)",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Subtotal",
            ),
        ),
    ]
