# Generated by Django 5.0.1 on 2025-12-16 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0012_add_invoice_number_and_transaction_items"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="paymenttransaction",
            new_name="payments_pa_invoice_05b731_idx",
            old_name="payments_pa_invoice_idx",
        ),
        migrations.RenameIndex(
            model_name="paymenttransactionitem",
            new_name="payments_pa_transac_ea4d69_idx",
            old_name="payments_pa_transac_idx",
        ),
        migrations.RenameIndex(
            model_name="paymenttransactionitem",
            new_name="payments_pa_involve_ef98f9_idx",
            old_name="payments_pa_involv_idx",
        ),
    ]
