# Generated by Django 5.0.1 on 2025-10-20 16:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "firebase_uid",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=128,
                        null=True,
                        unique=True,
                        verbose_name="Firebase UID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="Email")),
                ("first_name", models.CharField(blank=True, max_length=150, verbose_name="Nombre")),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=150, verbose_name="Apellido"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Admin"), ("player", "Player")],
                        default="player",
                        max_length=20,
                        verbose_name="Rol",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("is_staff", models.BooleanField(default=False, verbose_name="Staff")),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Fecha de registro"
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="Último acceso"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "ordering": ["-date_joined"],
                "indexes": [
                    models.Index(fields=["email"], name="users_user_email_6f2530_idx"),
                    models.Index(fields=["firebase_uid"], name="users_user_firebas_b8ee51_idx"),
                    models.Index(fields=["role"], name="users_user_role_36d76d_idx"),
                ],
            },
        ),
    ]
