# Generated by Django 5.0.1 on 2025-10-22 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="user",
            name="users_user_firebas_b8ee51_idx",
        ),
        migrations.RemoveField(
            model_name="user",
            name="firebase_uid",
        ),
    ]
