# Generated by Django 5.0.1 on 2025-10-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_firebase_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Imagen de perfil del usuario",
                null=True,
                upload_to="avatars/",
                verbose_name="Avatar",
            ),
        ),
    ]
