# Generated by Django 5.0.1 on 2025-10-21 21:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nombre de la organización"),
                ),
                (
                    "nit",
                    models.CharField(
                        help_text="Número de Identificación Tributaria",
                        max_length=50,
                        unique=True,
                        verbose_name="NIT",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Fecha de actualización"),
                ),
                (
                    "administrators",
                    models.ManyToManyField(
                        help_text="Usuarios administradores de esta organización",
                        related_name="administered_organizations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Administradores",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_organizations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organización",
                "verbose_name_plural": "Organizaciones",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["nit"], name="organizatio_nit_c03b56_idx"),
                    models.Index(fields=["name"], name="organizatio_name_537540_idx"),
                    models.Index(fields=["is_active"], name="organizatio_is_acti_1ffc28_idx"),
                ],
            },
        ),
    ]
