# Generated by Django 5.0.1 on 2025-10-31 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="organizations/logos/",
                verbose_name="Logo de la organización",
            ),
        ),
    ]
