# Generated by Django 5.0.1 on 2025-11-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_organization_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="organizations_logos/",
                verbose_name="Logo de la organización",
            ),
        ),
    ]
