# Generated by Django 5.0.1 on 2025-12-03 12:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("players", "0006_alter_playerprofile_gender"),
        ("tournaments", "0009_tournamentdivision_is_published_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "match_code",
                    models.CharField(
                        help_text="Unique match code within division (M1, M2, LM1, etc.)",
                        max_length=20,
                        verbose_name="Match Code",
                    ),
                ),
                (
                    "max_sets",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Maximum number of sets for this match (3-10)",
                        validators=[
                            django.core.validators.MinValueValidator(3),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Maximum Sets",
                    ),
                ),
                (
                    "points_per_set",
                    models.PositiveIntegerField(
                        default=15,
                        help_text="Points required to win a set (1-50)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(50),
                        ],
                        verbose_name="Points Per Set",
                    ),
                ),
                (
                    "match_type",
                    models.CharField(
                        choices=[("singles", "Singles"), ("doubles", "Doubles")],
                        help_text="Type of match (singles or doubles)",
                        max_length=10,
                        verbose_name="Match Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Current status of the match",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "round_number",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Round number in the bracket",
                        null=True,
                        verbose_name="Round Number",
                    ),
                ),
                (
                    "is_losers_bracket",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this match is in the losers bracket",
                        verbose_name="Losers Bracket",
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Scheduled date and time for the match",
                        null=True,
                        verbose_name="Scheduled At",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Actual start date and time of the match",
                        null=True,
                        verbose_name="Started At",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Completion date and time of the match",
                        null=True,
                        verbose_name="Completed At",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the match",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the match",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_matches",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        help_text="Division in which the match is played",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="tournaments.tournamentdivision",
                        verbose_name="Division",
                    ),
                ),
                (
                    "next_match",
                    models.ForeignKey(
                        blank=True,
                        help_text="Next match in the bracket that the winner will play",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="previous_matches",
                        to="matches.match",
                        verbose_name="Next Match",
                    ),
                ),
                (
                    "partner1",
                    models.ForeignKey(
                        blank=True,
                        help_text="Partner of player 1 for doubles matches",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_partner1",
                        to="players.playerprofile",
                        verbose_name="Partner 1",
                    ),
                ),
                (
                    "partner2",
                    models.ForeignKey(
                        blank=True,
                        help_text="Partner of player 2 for doubles matches",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_partner2",
                        to="players.playerprofile",
                        verbose_name="Partner 2",
                    ),
                ),
                (
                    "player1",
                    models.ForeignKey(
                        blank=True,
                        help_text="Player 1 or Team 1 player 1. Can be NULL for byes.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_player1",
                        to="players.playerprofile",
                        verbose_name="Player 1",
                    ),
                ),
                (
                    "player2",
                    models.ForeignKey(
                        blank=True,
                        help_text="Player 2 in singles. Can be NULL for byes.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_player2",
                        to="players.playerprofile",
                        verbose_name="Player 2",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Winner of the match (player or team player 1)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matches_won",
                        to="players.playerprofile",
                        verbose_name="Winner",
                    ),
                ),
                (
                    "winner_partner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Winner partner for doubles matches",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matches_won_as_partner",
                        to="players.playerprofile",
                        verbose_name="Winner Partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Match",
                "verbose_name_plural": "Matches",
                "ordering": ["division", "round_number", "match_code"],
            },
        ),
        migrations.CreateModel(
            name="Set",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "set_number",
                    models.PositiveIntegerField(
                        help_text="Set number (1, 2, 3, ...)", verbose_name="Set Number"
                    ),
                ),
                (
                    "player1_score",
                    models.PositiveIntegerField(
                        default=0, help_text="Score of player/team 1", verbose_name="Player 1 Score"
                    ),
                ),
                (
                    "player2_score",
                    models.PositiveIntegerField(
                        default=0, help_text="Score of player/team 2", verbose_name="Player 2 Score"
                    ),
                ),
                (
                    "winner",
                    models.CharField(
                        blank=True,
                        choices=[("player1", "Player 1"), ("player2", "Player 2")],
                        help_text="Winner of this set",
                        max_length=10,
                        null=True,
                        verbose_name="Winner",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Completion date and time of the set",
                        null=True,
                        verbose_name="Completed At",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        help_text="Match this set belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sets",
                        to="matches.match",
                        verbose_name="Match",
                    ),
                ),
            ],
            options={
                "verbose_name": "Set",
                "verbose_name_plural": "Sets",
                "ordering": ["match", "set_number"],
            },
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["division"], name="matches_mat_divisio_7c31e4_idx"),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["match_code"], name="matches_mat_match_c_f942f6_idx"),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["status"], name="matches_mat_status_a896a5_idx"),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["match_type"], name="matches_mat_match_t_bc2e9e_idx"),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["round_number"], name="matches_mat_round_n_3a6119_idx"),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["is_losers_bracket"], name="matches_mat_is_lose_f78301_idx"),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["player1", "player2"], name="matches_mat_player1_76ecd5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="match",
            unique_together={("division", "match_code")},
        ),
        migrations.AddIndex(
            model_name="set",
            index=models.Index(fields=["match"], name="matches_set_match_i_8fb6e4_idx"),
        ),
        migrations.AddIndex(
            model_name="set",
            index=models.Index(fields=["set_number"], name="matches_set_set_num_c1860e_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="set",
            unique_together={("match", "set_number")},
        ),
    ]
