# Generated by Django 5.0.1 on 2026-01-24 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='round_number',
            field=models.IntegerField(blank=True, help_text='Round number in the bracket', null=True, verbose_name='Round Number'),
        ),
    ]
