# Generated by Django 5.0.1 on 2026-01-26 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0002_alter_match_round_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Court or location where the match is played",
                max_length=50,
                null=True,
                verbose_name="Location",
            ),
        ),
    ]
